### ISSUE TITLE
Issue with collision system

### ISSUE THREAD

**Issue by Pricter** [azurite-engine/Azurite#56]
If, in game you press "W" key, making you go up, you are accelerated to insane speed, and once you reach the top, by spam clicking the "W" key, you can just slip outside the room like structure , allowing you to go out of the world

**Comment by PixelRifts** [comment]
Yep, it's a problem with the current character controller, it'll be fixed before the 1.0 release definitely

**Comment by Juyas** [comment]
since the character controller and the collision have been reworked, this problem should no longer appear
