### ISSUE TITLE
Issue with character controller

### ISSUE THREAD

**Issue by Pricter** [azurite-engine/Azurite#59]
if i am accelerated to a speed in direction left, and i press the right key (a), i am not moving in the right direction i am slowing down and sometimes it is not even slowing down, and sometimes i am accelerated for no reason if i release the right key

**Comment by Juyas** [comment]
it happens if collision forcefully stops your movement, the current character controller does not notice that and resets his movement -> there does the hidden acceleration come from.

**Comment by Juyas** [comment]
since the collisions and the character controller are reworked, this problem should no longer appear
