### ISSUE TITLE
Issue with tile rendering.

### ISSUE THREAD

**Issue by Pricter** [azurite-engine/Azurite#60]
This bug is related to the bug with collision system, the same here, when i am accelerated to insane speeds, Example: There is a block tile above me and i spam the w key, the tile start to jitter and small white lines appear between the tiles, and it happen for all the tiles, even though i am not even touching them

**Comment by Juyas** [comment]
its actually related to the character controller, since you effectively break the current version of the engine with that.
If the character controller is fixed or removed, it should be fine.

**Comment by athaun** [comment]
We are planning on removing the current character controller soon.
